#!/bin/bash

# Copyright 2013 John Leacox
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "$(whoami)" = "root" ]; then
	echo -e "Run script as a non-root user and without sudo\n"
	exit 1
fi

USER=$(whoami)

# Install bundler
echo -e "Installing bundler"
gem install bundler

# Remove lock files
rm Cheffile.lock > /dev/null 2>&1
rm Gemfile.lock > /dev/null 2>&1

# Get latest repo
git fetch -q origin
git reset --hard origin/master > /dev/null 2>&1
git clean -qdf

# Bundle and execute soloist
echo -e "Running soloist"
bundle
bundle exec soloist
